name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v5
      - name: Install Uv and set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
      - name: Install the project dependencies
        run: uv sync --locked --all-extras --dev
      - name: install the package
        run: uv run pip install -e ".[test]"
      - name: Run tests
        run: uv run pytest tests
      - name: Check README formatting
        run: uv run python -m cogapp --check README.md
